[project]
name = "2-agent-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logfire>=3.16.0",
    "openai-agents>=0.0.15",
]
